# ==========
# üì∑ C√°mara
# ==========

camera:
  # Resoluci√≥n de la c√°mara en p√≠xeles
  width: 2592
  height: 1944


# =========
# üìÅ Rutas
# =========

paths:
  # Directorio donde se guardar√°n las fotos
  photos: photos


# ===========================
# ‚è±Ô∏è Planificaci√≥n de tareas
# ===========================

scheduler:
  # Horas del d√≠a (0-23) para tomar fotos
  photo_hours: [10, 18]
  # Intervalo (en segundos) para medir la humedad del suelo
  moisture_interval: 10
  # Frecuencia (en segundos) de actualizaci√≥n de la pantalla
  display_interval: 0.5

# =====================
# üíß Sensor de humedad
# =====================

moisture:
  # Pin anal√≥gico al que est√° conectado el sensor de humedad
  pin: A0
  # Valor absoluto de humedad en seco
  raw_dry: 21550
  # Valor absoluto de humedad en mojado
  raw_wet: 7600
  # Valor de humedad (en porcentaje) considerado √≥ptimo
  optimal: 50


# ===========
# üí° LED RGB
# ===========

led_rgb:
  # Pines GPIO a los que est√°n conectados los canales del LED RGB
  pins:
    red: 17
    green: 27
    blue: 22

  # Frecuencia PWM (en Hz) para el control del LED RGB
  pwm_frequency: 500


# ============
# üñ•Ô∏è Pantalla
# ============

display:
  # Valor (en porcentaje) de humedad m√≠nimo antes de la activaci√≥n del indicador de humedad baja
  moisture_threshold: 30
  # Intervalo (en segundos) de parpadeo del indicador de humedad baja
  blink_interval: 1