# ==========
#  C谩mara
# ==========

camera:
  # Resoluci贸n de la c谩mara en p铆xeles
  width: 2592
  height: 1944


# =========
#  Rutas
# =========

paths:
  # Directorio donde se guardar谩n las fotos
  photos: photos


# ===========================
# 憋 Planificaci贸n de tareas
# ===========================

scheduler:
  # Horas del d铆a (0-23) para tomar fotos
  hours: [10, 18]


# =====================
#  Sensor de humedad
# =====================

moisture:
  # Pin anal贸gico al que est谩 conectado el sensor de humedad
  pin: A0
  # Valor absoluto de humedad en seco
  raw_dry: 21550
  # Valor absoluto de humedad en mojado
  raw_wet: 7600
  # Valor de humedad (en porcentaje) considerado 贸ptimo
  optimal: 50
